version: '3.8'

services:
  archon-server:
    build:
      context: ./python
      dockerfile: Dockerfile.server
    ports:
      - "8181:8181"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SERVICE_DISCOVERY_MODE=docker_compose
      - LOG_LEVEL=INFO
      - ARCHON_SERVER_PORT=8181
      - ARCHON_MCP_PORT=8051
      - ARCHON_AGENTS_PORT=8052
      - AGENTS_ENABLED=true

  archon-agents:
    build:
      context: ./python
      dockerfile: Dockerfile.agents
    ports:
      - "8052:8052"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SERVICE_DISCOVERY_MODE=docker_compose
      - LOG_LEVEL=INFO
      - ARCHON_AGENTS_PORT=8052
      - ARCHON_SERVER_PORT=8181

  archon-mcp:
    build:
      context: ./python
      dockerfile: Dockerfile.mcp
    ports:
      - "8051:8051"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - SERVICE_DISCOVERY_MODE=docker_compose
      - TRANSPORT=sse
      - LOG_LEVEL=INFO
      - API_SERVICE_URL=http://archon-server:8181
      - AGENTS_ENABLED=true
      - AGENTS_SERVICE_URL=http://archon-agents:8052
      - ARCHON_MCP_PORT=8051
      - ARCHON_SERVER_PORT=8181
      - ARCHON_AGENTS_PORT=8052

  archon-frontend:
    build: ./archon-ui-main
    ports:
      - "3737:3737"
    environment:
      - VITE_API_URL=http://localhost:8181
      - VITE_ARCHON_SERVER_PORT=8181
      - ARCHON_SERVER_PORT=8181
      - HOST=localhost
      - PROD=false